version: "3.8"
services:
  postgres-db:
    container_name: postgres
    image: "postgres" # use latest official postgres version
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-db/data:/var/lib/postgresql/data
